---
- hosts: all
  connection: local
  
  roles:
    - role: ableton.nix

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Install system updates for RPM systems
      dnf: name=* state=latest update_cache=yes
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_distribution == 'Generic' 
      become: true 

    - name: Install system updates for DEB systems
      apt: upgrade=dist update_cache=yes
      when: ansible_distribution == "Ubuntu" or ansible_distribution == 'Debian'
      become: true 

  tasks:
    # - name: Distribution
    #   debug: msg="{{ ansible_distribution }}"
    # - name: Distribution version
    #   debug: msg="{{ ansible_distribution_version}}"
    # - name: Distribution major version
    #   debug: msg="{{ ansible_distribution_major_version }}"

    # - include_tasks: tasks/locale.yml

    # - name: "Install apt cmd line apps"
    #   apt:
    #     state: latest
    #     name:
    #       - unzip
    #   become: true

    # - include_tasks: tasks/aws-vault.yml
    #   when: install_aws_vault

  post_tasks:
    - name: Autoremove unneeded packages installed as dependencies
      apt: 
        autoclean: yes
        autoremove: yes
      become: true
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

    - name: Autoremove unneeded packages installed as dependencies
      ansible.builtin.dnf:
        autoremove: yes
      become: true
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora' or ansible_distribution == 'Generic' 