---

- name: "sshd - Search for Port 2222 in sshd_config"
  shell: "grep -s -i '^Port 2222' /etc/ssh/sshd_config"
  register: port2222
  ignore_errors: true
  become: true

- name: "sshd - rc"
  debug:
    var: port2222.rc

- name: "sshd - re-install to fix host keys"
  # https://derkoe.dev/blog/development-environment-in-wsl2/
  block:

  - name: "sshd - uninstall purge"
    apt:
      state: absent
      purge: true
      name:
        - openssh-server
    become: true

  - name: "sshd - reinstall latest"
    apt:
      state: latest
      name:
        - openssh-server
      update_cache: yes
      cache_valid_time: 3600
    become: true

  when: port2222.rc != 0
  become: true

- name: "sshd - configure on port 2222"
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#Port 22" 
    line: "Port 2222"
    firstmatch: true
    state: present
  become: true

- name: "sshd - PasswordAuthentication to default"
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication no'
    line: "#PasswordAuthentication yes"
  become: true

  #TODO Autostart
